import type { Metadata } from "next";
import { Merriweather_Sans } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const merriweather = Merriweather_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "LearnLink",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className="hide-scrollbar">
        <body
          className={`${merriweather.className} min-h-screen flex w-full flex-col bg-black text-white antialiased`}
        >
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
